version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - ls -l vendor/cache
      - cp config/database.codebuild.yml config/database.yml
      - gem install bundler
      - bundle install --local
  pre_build:
    commands:
      - RAILS_ENV=test rails db:create
      - RAILS_ENV=test rails db:migrate
  build:
    commands:
      - bundle exec rake test:pipeline
  post_build:
    commands:
      - RAILS_ENV=test rails db:drop
artifacts:
  files:
    - pipeline_files.json
    # - location
  #discard-paths: yes
  #base-directory: location

