version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - cp config/database.codebuild.yml config/database.yml
      - gem install bundler
      - bundle install
      # - command
      # - command
  pre_build:
    commands:
      - RAILS_ENV=test rails db:create
      - RAILS_ENV=test rails db:migrate
  build:
    commands:
      - bundle exec rake test
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location

