version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - env
      - env | grep -i pipeline
      - git log --oneline | nl -v0 | sed 's/^ \+/&HEAD~/'
        #- gem install bundler
        #- bundle package
      #- bundle install --deployment
      # - command
  #pre_build:
    #commands:
  build:
    commands:
      - ruby files.rb > pipeline_files.json
      # - command
  #post_build:
    #commands:
      # - command
      # - command
cache:
  paths:
    - 'vendor/**/*'

      #artifacts:
      # files:
      #- '**/*'
    # - test_files.json
    # - location
  #discard-paths: yes
  #base-directory: location

