version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
  #  commands:
      # - command
      # - command
  #pre_build:
    #commands:
  build:
    commands:
      - ruby files.rb > pipeline_files.json
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
     - test_files.json
    # - location
  #discard-paths: yes
  #base-directory: location

